### ISSUE TITLE
Crear settings.py para configurar el user agent y robots.txt

### ISSUE THREAD

**Issue by xantilopez** [equipoUOC/CarrefourTracker#8]

**Comment by isrosrey** [comment]
Relacionado con esto creo que podría servir de ayuda el siguiente enlace, lo revisamos más adelante si nos da tiempo porque cambiaría bastante la estructura del proyecto:
https://docs.scrapy.org/en/latest/intro/tutorial.html

**Comment by isrosrey** [comment]
al crear el proyecto siguiendo el tutorial de la documentación oficial de scrapy ya se crea el settings.py y he configurado el user agent "PriceTracker (estudiante)" en el mismo
